---HCP_address_cleanup_SOP_case_1.5

spark2-shell  --master yarn --driver-memory 10G --num-executors 10 --executor-memory 10G --conf spark.port.maxRetries=100 --conf sparnf=TRUE  --queue fido --conf spark.sql.hive.convertMetastoreParquet=false --conf spark.hadoop.hive.exec.dynamic.partition.mode=nonstrict --conf spark.sql.autoBroadcastJoinThreshold=-1

spark.sparkContext.setLogLevel("ERROR")

spark.sql(" select count(*) from all_all_r_all_bkp.hcp_addr_cleanup_case1").show

spark.sql(" create table all_all_r_all_bkp.ods_contacts_addr_case_1_5 like all_all_b_usa_crmods.ods_contacts_addr")
spark.sql("insert into all_all_r_all_bkp.ods_contacts_addr_case_1_5 select * from all_all_b_usa_crmods.ods_contacts_addr")


spark.sql("""with req_data as (select id,address_mdm_id__c,account_odw__c,addr_odw_id,address_odw__c from all_all_r_all_bkp.hcp_addr_cleanup_case1 y where y.address_mdm_id__c is null and y.address_odw__c is not null and y.sf_id is null and y.addr_o_addr_odw_id is null and y.addr_o_sf_id is null and acc_od_account_check=FALSE), dice_records as ( select dice.*,ac.* from (SELECT dice.mobile_id_vod__c ,   dice.fax_2_vod__c , dice.fax_vod__c ,   dice.city_vod__c ,dice.address_line_2_vod__c ,dice.name , dice.source_vod__c , dice.shipping_vod__c ,  dice.include_in_territory_assignment_vod__c , dice.appt_required_vod__c ,   dice.billing_vod__c ,  dice.account_vod__c ,   dice.primary_vod__c ,   dice.isdeleted , dice.id  , dice.address_odw__c , dice.best_times_vod__c , dice.cass_certified__c ,dice.address_mdm_id__c , dice.inactive_vod__c , dice.staff_notes_vod__c , dice.office_notes_vod__c , dice.license_valid_to_sample_vod__c , dice.sample_status_vod__c , dice.dea_license_address_vod__c ,dice.zip_4_vod__c ,dice.zip_vod__c , dice.state_vod__c , dice.phone_2_vod__c , dice.phone_vod__c , dice.state_distributor_license_exempt_vod__c , dice.nvs_core_secondary_license__c , dice.map_vod__c , dice.sample_send_status_vod__c ,  dice.nvs_core_novartis_unique_id__c nvs_core_novartis_unique_id__c_addr,dice.createddate FROM req_data rd left join  ph_com_p_usa_veeva.address_vod__c dice on dice.id=rd.id and dice.address_odw__c=rd.address_odw__c and dice.isdeleted=false and where dice.createddate < '2022-09-26') dice  JOIN (select id as acct_id,account_odw__c,nvs_core_novartis_unique_id__c from ph_com_p_usa_veeva.account where ispersonaccount = true and isdeleted=false and recordtypeid='0121O000001CG6UQAW') ac on trim(ac.acct_id) = trim(dice.account_vod__c))

insert into all_all_b_usa_crmods.ods_contacts_addr SELECT dice.mobile_id_vod__c mobile_id,  null email4,  null email3,  null email2,  null email1, dice.fax_2_vod__c contact_fax_2, dice.fax_vod__c contact_fax_1,  null  city_post, dice.city_vod__c city,dice.address_line_2_vod__c addr_line_2,dice.name addr_line_1, dice.source_vod__c src, dice.shipping_vod__c shipping,  null mig_stat, null mailing, dice.include_in_territory_assignment_vod__c include_in_terr_asgnmt, dice.appt_required_vod__c appt_reqd,  null cc_flag, null business, dice.billing_vod__c billing,  null account, null home,  null contact_name,  null edge_id,  null par_edge_id,  null sonic_id,  null cam_key, dice.account_vod__c as  acct_id,  null cont_id, dice.primary_vod__c PRIMARY,  null physician_key, null  sf_owner_id, dice.isdeleted sf_is_deleted, dice.id sf_id,  null addr_per_id, SUBSTR(dice.account_odw__c, 2) contacts_odw_id , substr( trim(dice.address_odw__c), 3 ) contacts_addr_odw_id,  null mdm_valid_addr_ind, dice.best_times_vod__c best_times, dice.cass_certified__c cass_certified,dice.address_mdm_id__c mdm_addr_id,  null dly_scrub_date,  null mth_scrub_date,  null addr_post_line_2,  null addr_post_line_1,  null fax_2,  null fax_1, 300 batch_id_insert,'VOD' rec_insert_by, current_timestamp() rec_modify_date, dice.createddate rec_insert_date, dice.inactive_vod__c inactive, dice.staff_notes_vod__c staff_notes, dice.office_notes_vod__c office_notes, dice.license_valid_to_sample_vod__c lic_valid_to_sample, dice.sample_status_vod__c sample_stat,  null dea_auth_stat_date,  null dea_auth_stat,  null dea_sched_cls, dice.dea_license_address_vod__c dea_lic_addr,  null dea_expirn_date,  null dea,  null zip_post,  null zip_4_post,dice.zip_4_vod__c zip_4,dice.zip_vod__c zip, null cntry_code,dice.state_vod__c state,  null phone_3, dice.phone_2_vod__c phone_2, dice.phone_vod__c phone_1,  null scrub_req, null cnty,  null siebel_id,  301 batch_id_update, 'VOD' rec_modify_by ,null sample_eligibility_flag, dice.state_distributor_license_exempt_vod__c , dice.nvs_core_secondary_license__c nvs_core_secondary_license__c, dice.map_vod__c maps, dice.sample_send_status_vod__c sample_send_status_vod__c,  dice.nvs_core_novartis_unique_id__c_addr nvs_core_novartis_unique_id__c  FROM dice_records dice """)